name: Bi-Weekly GitHub Stats Aggregation

on:
  schedule:
    - cron: '0 0 */14 * *' # Run every 14 days at midnight
  workflow_dispatch:

jobs:
  aggregate-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install requests

    - name: Run aggregation script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python aggregate_stats.py

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Commit changes
      run: |
        git add data/aggregated_referrers.json data/aggregated_paths.json
        git commit -m "Update aggregated JSON files"

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push
