name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install requests

    - name: Debug Environment Variables
      run: |
        echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
        echo "QUEST_TOKEN=${{ secrets.QUEST_TOKEN }}"
        echo "Running script..."

    - name: Run update script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        QUEST_TOKEN: ${{ secrets.QUEST_TOKEN }}
      run: python update_stats.py

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Commit changes
      run: |
        git add data/*.json
        git status
        if ! git diff-index --quiet HEAD; then
          git commit -m "Update JSON files"
        else
          echo "No changes to commit"
        fi

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push
