name: Update Downloads
on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  push:
    branches:
      - main
jobs:
  update-downloads:
    runs-on: ubuntu-latest
    env:
      QUEST_TOKEN: ${{ secrets.QUEST_TOKEN }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false  # Disable automatic token authentication

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run update script
      run: |
        python update_shield.py

    - name: Push to Public Repo
      env:
        GITHUB_TOKEN: ${{ secrets.SHIELDS_TOKEN }}
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git clone https://x-access-token:${{ secrets.SHIELDS_TOKEN }}@github.com/Alope489/shields.git public-repo
        cp shields/badge_data.json public-repo/
        cp shields/release_badge_data.json public-repo/
        cd public-repo
        git add badge_data.json release_badge_data.json
        if git diff --cached --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        git commit -m "Update download statistics and release information"
        git push --force origin main
